version: '3'
services:
  cassandra:
    image: cassandra:3.11.6
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_USER=user
      - CASSANDRA_PASSWORD=pass
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=128M
    container_name: cassandra
    restart: always
    # volumes:
    #   - ./out/cassandra_data:/var/lib/cassandra
